### ISSUE TITLE
/var/spool/slurmd/job81640/slurm_script: conda: command not found

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#44]
quand j'envoie la commande suivante 

`sbatch --array=1-7 /ip29/ilafores_group/rosaelle/syncom/scripts/kofamscan.sh`

ça fonctionne, mais quand c'est rosa qui l'envoie ça ne fonctionne pas. On a ajouté `module load StdEnv/2020` à son .bashrc et elle travaille sous def-ilafores. Voir log: 
`/ip29/ilafores_group/rosaelle/syncom/slurm_logs/kofamscan-81639_1.out `

**Comment by jflucier** [comment]
le log:

```
...loading env
/var/spool/slurmd/job81640/slurm_script: conda: command not found
...job started on 2022.10.14-13.31.07
...copying the Leaf26 sample
...predicting ORFs with Prodigal
/var/spool/slurmd/job81640/slurm_script: prodigal: command not found
...annotating predicted genes with KOfamscan
/project/6047190/common/kofam_scan/lib/kofam_scan/executor.rb:84:in `initialize': No such file or directory @ rb_sysopen - /localscratch/rosaelle.81640.0/Leaf26_KO/Leaf26.faa (Errno::ENOENT)
        from /project/6047190/common/kofam_scan/lib/kofam_scan/executor.rb:84:in `open'
        from /project/6047190/common/kofam_scan/lib/kofam_scan/executor.rb:84:in `query_list'
        from /project/6047190/common/kofam_scan/lib/kofam_scan/executor.rb:170:in `check_query_names'
        from /project/6047190/common/kofam_scan/lib/kofam_scan/executor.rb:23:in `execute'
        from /project/6047190/common/kofam_scan/lib/kofam_scan/executor.rb:8:in `execute'
        from /project/6047190/common/kofam_scan/lib/kofam_scan/cli.rb:21:in `run'
        from /project/def-ilafores/common/kofam_scan/exec_annotation:7:in `<main>'
...copying results to ip29
...job finished on 2022.10.14-13.31.08

```

regarde ton fichier ~/.bashrc et inclut la partie qui load conda au ~/.bashrc de rosaelle
