### ISSUE TITLE
Erreur avec MicrobeAnnotator

### ISSUE THREAD

**Issue by jorondo1** [jflucier/ILL_pipelines#72]
Quand je roule en local (et sans anchor)
```
MAG_DIR=/home/def-ilafores/analysis/projet_PROVID19/Saliva/MAG_analysis
bash $ILL_pipelines/scripts/annotate_bins.sh -o $MAG_DIR/Annotation -t 72 -drep $MAG_DIR/drep_genomes/dereplicated_genomes
```
une fois l'étape d'annotation terminée, MicrobeAnnotator commence et ça crash aussitôt:
```
WARNING: While bind mounting '/home:/home': destination is already in the mount point list
2023-11-01 21:59:00,220 [INFO]:  ---- This is MicrobeAnnotator v2.0.5 ---- 
2023-11-01 21:59:00,220 [INFO]: Validating user inputs
2023-11-01 21:59:00,222 [INFO]: Passed
2023-11-01 21:59:00,222 [INFO]: Processing 130 files. I will run 36 files in parallel with 2 threads per file.
Traceback (most recent call last):
  File "/miniconda3/envs/microbeannotator/bin/microbeannotator", line 4, in <module>
    __import__('pkg_resources').run_script('microbeannotator==2.0.5', 'microbeannotator')
  File "/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/pkg_resources/__init__.py", line 720, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1559, in run_script
    exec(code, namespace, namespace)
  File "/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator-2.0.5-py3.7.egg/EGG-INFO/scripts/microbeannotator", line 994, in <module>
    main()
  File "/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator-2.0.5-py3.7.egg/EGG-INFO/scripts/microbeannotator", line 295, in main
    refdata.get_databases()
  File "/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator-2.0.5-py3.7.egg/EGG-INFO/scripts/microbeannotator", line 109, in get_databases
    with open(self.ko_profiles_db / 'common.list', 'r') as infile:
OSError: [Errno 5] Input/output error: '/cvmfs/datahub.genap.ca/vhost34/def-ilafores/MicrobeAnnotator_DB/kofam_data/profiles/common.list'

```

J'ai pourtant réussi avec mes données Moss, mais j'arrive pas à figure out ce que j'ai fait différent

**Comment by jflucier** [comment]
microannotator n'est plus dans /fast/def-ilafores/MicrobeAnnotator_DB
